max_force: 10.0                # Maximum thrust per thruster [Newtons]
sending_time: 1.0              # Command sending interval [Seconds]
thruster: 6                    # Total number of thrusters
threshold: 0.1                 # Minimum change in force required to send a new command [Newtons]
dead_zone: 0.2                 # Joystick dead zone threshold [0.0 - 1.0]

pose: /bluerov2/pose_gt        # Ground truth pose topic (geometry_msgs/msg/Pose)
                               # Set to 'NONE' to disable pose feedback

# Joystick Axis to Thruster Mapping
# Each axis (ax0 - ax5) maps to the 6 thrusters.
# Values:
#   - Positive/Negative numbers: Relative contribution and direction
#   - 0: No contribution

keymap:
  ax0: [-1, -1, -1, -1,  0,  0]  # Left joystick vertical    -> Forward/Backward movement
  ax1: [-1,  1,  1, -1,  0,  0]  # Left joystick horizontal  -> Left/Right movement (strafe)
  ax2: [ 0,  0,  0,  0, -1,  1]  # Right joystick vertical   -> Submerge/Emerge
  ax3: [ 0,  1, -1,  0,  0,  0]  # Right joystick horizontal -> Rotate (yaw)
  ax4: [ 0,  0,  0,  0,  0,  0]  # Left trigger              -> Unused
  ax5: [ 0,  0,  0,  0,  0,  0]  # Right trigger             -> Unused
