services:
  simulator_desert-bluerov:
    container_name: simulator_desert-bluerov
    build:
      context: .
      dockerfile: Dockerfile
    image: simulator_desert-bluerov_img
    stdin_open: true
    tty: true
    privileged: true # required for /dev/input (keyboard) access
    environment:
      DISPLAY: "${DISPLAY}"
      QT_X11_NO_MITSHM: "1"
      QT_QPA_PLATFORM: "xcb"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/input:/dev/input:rw
