max_speed: 10.0                 # Newton
sending_time: 1.0               # Seconds
thruster: 6                     # Number of different Thruster
threshold: 0.1                  # Threshold for sending message
keymap:
  ax0: [-1, -1, -1, -1, 0, 0]     # Vertical Left Axis
  ax1: [-1, 1, 1, -1, 0, 0]       # Horizontal Left
  ax2: [0, 0, 0, 0, -1, 1]        # Vertical Right Axis
  ax3: [0, 1, -1, 0, 0, 0]        # Horizontal Right Axis
  ax4: [0, 0, 0, 0, 0, 0]         # Left Trigger
  ax5: [0, 0, 0, 0, 0, 0]         # Right Trigger
